#
# 
#
version: '3.8'

services:
  webserver:
    build: apache_image
    image: phaustin/apache:jan23
    container_name: apache_jan23
    ports:
      - "${TEXT_PORT}:80"
    volumes:
      - ./notebooks/_build/html:/usr/local/share/a301
      - ./settings:/srv/settings
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: bash -c
            "cp -a /srv/settings/httpd.conf /usr/local/apache2/conf/httpd.conf
             && httpd-foreground
            "
#
# based on pangeo base_image -- sets up conda
# and user jovyan -- defers environment using ONBUILD
#
  base_image:
    build:
      context: base_image
      dockerfile: Dockerfile
    image: phaustin/base-image:jan23
    depends_on: [notebook_jan26]
    container_name: base-image
#
# jupyterhub that launches notebooks
#
  a301hub_jan26:
    build: hub_image
    image: phaustin/hub301:jan26
    container_name: hub301_jan26
    depends_on: [base_image]
    ports:
      - ${NB_PORT}:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net_jan26
#
# actual notebook with fully installed environment
#
  notebook_jan26:
    image: phaustin/a301book:jan26
    build:
      context: notebook_image
    container_name: a301book_jan26

# force the network name to be "jupyterhub"
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'jupyterhub'
networks:
    net_jan26:
      driver: bridge
      name: net_jan26


