#
# 
#
version: '3.8'

services:
  a448_webserver:
    build: apache_image
    image: phaustin/a448_apache:jan27
    container_name: a448_apache_jan27
    ports:
      - "${TEXT_PORT}:80"
    volumes:
      - ./notebooks/_build/html:/usr/local/share/a448
      - ./settings:/srv/settings
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: bash -c
            "cp -a /srv/settings/httpd.conf /usr/local/apache2/conf/httpd.conf
             && httpd-foreground
            "
#
# based on pangeo base_image -- sets up conda
# and user jovyan -- defers environment using ONBUILD
#
  a448base_image:
    build:
      context: base_image
      dockerfile: Dockerfile
    image: phaustin/a448_base_image:jan27
    depends_on: [a448book_jan26]
    container_name: a448_base_image
#
# jupyterhub that launches notebooks
#
  a448hub_jan26:
    build: hub_image
    image: phaustin/hub448:jan26
    container_name: hub448_jan26
    depends_on: [a448base_image]
    ports:
      - ${NB_PORT}:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - a448net_jan26
#
# actual notebook with fully installed environment
#
  a448book_jan26:
    image: phaustin/a448book:jan26
    build:
      context: a448book_image
    container_name: a448book_jan26

  alison_mar08:
    image: phaustin/alison:mar08
    build:
      context: alison_image
    container_name: alison_mar08

  andersen_feb10:
    image: phaustin/andersen:feb10
    build:
      context: andersen_image
    container_name: andersen_feb10

  justin_feb10:
    image: phaustin/justin:feb10
    build:
      context: justin_image
    container_name: justin_feb10

  marjolein_feb10:
    image: phaustin/marjolein:feb10
    build:
      context: marjolein_image
    container_name: marjolein_feb10

  shuting_feb10:
    image: phaustin/shuting:feb10
    build:
      context: shuting_image
    container_name: shuting_feb10
    
# force the network name to be "jupyterhub"
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'jupyterhub'
networks:
    a448net_jan26:
      driver: bridge
      name: a448net_jan26


